[env]
TERM = "xterm-256color"

[cursor]
unfocused_hollow = true

[font]
size = 15

[font.normal]
family = "CaskaydiaCove Nerd Font"

[scrolling]
history = 4000

[terminal.shell]
program = "/bin/zsh"
args = ["-l","-c","tmux attach || tmux"]
